### ISSUE TITLE
executing procedure after `adv.keyval` results in panic

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#893]
When I run `cargo test` on `miden-base` on the branch associated with the code snippet below I receive the following errors:

```
failures:

---- test_validate_id_fails_on_insuficcient_ones stdout ----
thread 'test_validate_id_fails_on_insuficcient_ones' panicked at 'last op index in decorator list should be less than number of ops', /Users/f/.cargo/git/checkouts/miden-vm-3db6be6805d1979c/544d06e/core/src/program/blocks/span_block.rs:402:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_account_type stdout ----
thread 'test_account_type' panicked at 'last op index in decorator list should be less than number of ops', /Users/f/.cargo/git/checkouts/miden-vm-3db6be6805d1979c/544d06e/core/src/program/blocks/span_block.rs:402:9

---- test_get_item stdout ----
thread 'test_get_item' panicked at 'last op index in decorator list should be less than number of ops', /Users/f/.cargo/git/checkouts/miden-vm-3db6be6805d1979c/544d06e/core/src/program/blocks/span_block.rs:402:9

---- test_set_code_is_not_immediate stdout ----
thread 'test_set_code_is_not_immediate' panicked at 'last op index in decorator list should be less than number of ops', /Users/f/.cargo/git/checkouts/miden-vm-3db6be6805d1979c/544d06e/core/src/program/blocks/span_block.rs:402:9

---- test_get_child_tree_item stdout ----
thread 'test_get_child_tree_item' panicked at 'last op index in decorator list should be less than number of ops', /Users/f/.cargo/git/checkouts/miden-vm-3db6be6805d1979c/544d06e/core/src/program/blocks/span_block.rs:402:9

---- test_set_code_succeeds stdout ----
thread 'test_set_code_succeeds' panicked at 'last op index in decorator list should be less than number of ops', /Users/f/.cargo/git/checkouts/miden-vm-3db6be6805d1979c/544d06e/core/src/program/blocks/span_block.rs:402:9

---- test_set_item stdout ----
thread 'test_set_item' panicked at 'last op index in decorator list should be less than number of ops', /Users/f/.cargo/git/checkouts/miden-vm-3db6be6805d1979c/544d06e/core/src/program/blocks/span_block.rs:402:9
```

I suspect that the execution of a procedure immediately after a decorator breaks the assembler as it has trouble building the span block.  I'm not certain of this and it should be investigated.

https://github.com/0xPolygonMiden/miden-base/blob/367466494fac84a808d77e445b75f6ef6e6500dd/miden-lib/asm/sat/account.masm#L304-L311

```
export.authenticate_procedure.1
    # load the index of the procedure root onto the advice stack
    adv.keyval
    # => [PROC_ROOT]

    # load the account code root onto the stack
    exec.layout::get_acct_code_root swapw
    # => [PROC_ROOT, CODE_ROOT]
```

**Comment by bobbinth** [comment]
This is probably related to https://github.com/0xPolygonMiden/miden-vm/pull/871.

**Comment by tohrnii** [comment]
Maybe we should consider treating AsmOp and advice injectors differently instead of clubbing them under decorators to avoid confusion like this in the code.

**Comment by bobbinth** [comment]
@plafer - I think this may have been fixed with the recent decorator refactoring. Could you check?

**Comment by plafer** [comment]
Confirmed that having a decorator right before a procedure call no longer results in an error, so closing.
